# Generated by Django 5.0.6 on 2024-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.TextField(),
        ),
    ]
