# Generated by Django 5.0.6 on 2024-09-07 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_code_text_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
