# Generated by Django 5.0.6 on 2024-09-08 02:16

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_text_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notifications/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'mp4', 'mpeg', 'avi', 'webm', 'mp3', 'wav', 'oog', 'wv', 'wma'])])),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('video', 'Video'), ('photo', 'Photo'), ('audio', 'Audio')], editable=False, max_length=31, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False, editable=False)),
                ('spent_time', models.TimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ('-created_at',),
            },
        ),
    ]
