# Generated by Django 5.0.6 on 2024-09-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ids',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
    ]
