# Generated by Django 5.0.6 on 2024-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
