# Generated by Django 5.0.6 on 2024-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_groupquizpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquizpart',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupquizpart',
            name='message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
