# Generated by Django 5.0.6 on 2024-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_test_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
