# Generated by Django 5.0.6 on 2024-07-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_groupquizpart_group_id_groupquizpart_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupquizpart',
            name='user',
        ),
    ]
