# Generated by Django 5.0.6 on 2024-07-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_remove_question_test_telegramprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
