# Generated by Django 5.0.6 on 2024-07-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_remove_groupquizpart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquizpart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
