# Generated by Django 5.0.6 on 2024-07-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_groupquizpart_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquizpart',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
