# Generated by Django 5.0.6 on 2024-07-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_groupquizpart_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquizpart',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
