# Generated by Django 5.0.6 on 2024-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
