# Generated by Django 5.0.6 on 2024-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_groupquizpart_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquizpart',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
