# Generated by Django 5.0.6 on 2024-07-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_telegramprofile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
