# Generated by Django 5.0.6 on 2024-07-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_groupquizpart_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquizpart',
            name='data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='tgbot.data'),
        ),
    ]
