# Generated by Django 5.0.6 on 2024-07-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_quiz_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_answers', models.IntegerField(blank=True, default=0, null=True)),
                ('correct_answers', models.IntegerField(blank=True, default=0, null=True)),
                ('spend_time', models.IntegerField(blank=True, default=0, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('quiz_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tgbot.quizpart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts', to='tgbot.telegramprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='tgbot_userq_created_2bb5df_idx')],
            },
        ),
    ]
