# Generated by Django 5.0.6 on 2024-09-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_groupquizpart_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='is_notif',
            field=models.BooleanField(default=True),
        ),
    ]
