# Generated by Django 5.0.6 on 2024-09-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_telegramprofile_is_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='quiz_number',
            field=models.IntegerField(default=5),
        ),
    ]
