# Generated by Django 5.0.6 on 2024-09-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_telegramprofile_quiz_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='bot_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
